import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import HeroSection from "@/components/HeroSection";
import AboutUs from "@/components/AboutUs";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "YOLO | Digital Marketing Company",
  description: "Generated by YOLO Digital Myanmar.",
  openGraph: {
    title: "YOLO | Digital Marketing Company",
    images: [
      {
        url: "yolologo.svg",
      },
    ],
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        // style={{ backgroundColor: "#530ffe07" }}
        className={inter.className}
      >
        <Header />
        <HeroSection />
        <AboutUs />
        {children}
      </body>
    </html>
  );
}
