import { Inter } from "next/font/google";
import Header from "@/components/Header";
import HeroSection from "@/components/HeroSection";
import AboutUs from "@/components/AboutUs";
import Services from "@/components/Services";
import Dialogue from "@/components/Dialogue";
import Contact from "@/components/Contact";
import Footer from "@/components/Footer";
import Projects from "@/components/Projects";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "YOLO | Digital Marketing Company",
  metadataBase: new URL("http://localhost:3000/"),
  description: "Generated by YOLO Digital Myanmar.",
  openGraph: {
    title: "YOLO | Digital Marketing Company",
    images: [
      {
        url: "../public/yolologo.svg",
      },
    ],
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-blue-50">
        <Header />
        <HeroSection />
        <AboutUs />
        <Projects />
        <Services />
        <Dialogue />
        <Contact />
        <Footer />
        {/* {children} */}
      </body>
    </html>
  );
}
